---
title: "Exp_serre"
author: "Emilie Champagne"
date: "2 juillet 2019"
output: html_document
---
```{r Packages, echo=FALSE, message=FALSE}
library(dplyr)
library(Rmisc)
library(knitr)
```

##Résultats des mesures d'humidité du sol - 26 juin

À noter qu'il y a une erreur, un des sac a été noté comme ERS-50-18, mais il n'existe aucun érable de 2050. Selon les tailles d'échantillons, je soupçonne que c'est un érable au niveau de stress hydrique 2.

Stress: niveau d'irrigation (0= 1000 ml, 1= 500 ml, 2= 300 ml)

Percent: pourcentage d'humidité du sol

```{r Computing soil humidity, echo=FALSE}
#Loading data & adjusting factors levels to be similar to other data file
key <- read.table("./Key.txt", header=TRUE, colClasses = c("factor", "character", rep("factor", times=4)))
key$Prov <- replace(key$Prov, key$Prov=="2018", "18")
key$Prov <- replace(key$Prov, key$Prov=="2050", "50")
key$Prov <- replace(key$Prov, key$Prov=="2080", "80")
key$Prov <- as.factor(key$Prov)

humidity <- read.table("./Poids_26juin.txt", header=TRUE, colClasses = c("character", rep("factor", times=3), rep("numeric", times =4)), dec=",")

#Computing soil humidity
humidity$Percent <- (((humidity$M_hum - humidity$M_sac) - (humidity$M2 - humidity$M_sac))/(humidity$M_hum - humidity$M_sac))*100

#Merging the two files together
levels <- union(levels(key$Esp), levels(humidity$Esp)) #Needed for the variable to stay in factor format
levels_ID <- union(levels(key$ID), levels(humidity$ID))

humidity <- left_join(mutate(humidity, Esp=factor(Esp, levels=levels), ID=factor(ID, levels=levels_ID)), mutate(key, Esp=factor(Esp, levels=levels), ID=factor(ID, levels=levels_ID)), by = c("Esp", "Prov", "ID")) #Joining both file with all rows in humidity but not all rows in key

#Computing means
humidity <- humidity[-which(humidity$Esp == "ERS" & humidity$Prov == "50"),]#Removing a mistake 

kable(summarySE(humidity, measurevar= "Percent", groupvars=c("Esp","Stress"), na.rm = TRUE), digits=2)

```

